use_frameworks!

platform :ios, '10.0'

target 'ObjectOnDisk_Example' do
  pod 'ObjectOnDisk', :path => '../', :testspecs => ['Tests']

  target 'ObjectOnDisk_Tests' do
    inherit! :search_paths
  end
end
